// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: test.jflex


@SuppressWarnings("fallthrough")
class GeneratedLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\3\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\0\1\16\1\17\11\20\1\0\1\21"+
    "\1\22\1\23\1\24\2\0\6\25\24\26\1\27\1\30"+
    "\1\31\1\0\1\26\1\0\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\2\26\1\40\1\26\1\41\1\42\1\26"+
    "\1\43\1\44\2\26\1\45\1\46\1\47\1\50\1\51"+
    "\1\26\1\52\2\26\1\53\1\54\1\55\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\10\20\1\23\1\1\1\24"+
    "\1\25\1\0\1\26\1\27\3\0\1\30\1\31\1\32"+
    "\7\20\1\33\4\20\1\34\1\35\1\36\22\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\u0142\0\u0170"+
    "\0\56\0\u019e\0\u01cc\0\u01fa\0\u0228\0\56\0\56\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\56"+
    "\0\u03c6\0\56\0\56\0\270\0\56\0\56\0\u03f4\0\u0422"+
    "\0\u0450\0\56\0\56\0\56\0\u047e\0\u04ac\0\u04da\0\u0508"+
    "\0\u0536\0\u0564\0\u0592\0\u0228\0\u05c0\0\u05ee\0\u061c\0\u064a"+
    "\0\56\0\56\0\u0450\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730"+
    "\0\u075e\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0"+
    "\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\26\1\2\1\27"+
    "\1\25\1\30\1\31\1\25\1\32\1\33\1\34\4\25"+
    "\1\35\1\25\1\36\1\25\1\37\1\25\1\40\1\41"+
    "\1\42\57\0\2\3\76\0\1\43\32\0\5\44\1\45"+
    "\50\44\6\0\1\46\47\0\7\47\1\0\20\47\1\50"+
    "\25\47\17\0\2\20\31\0\1\51\22\0\2\20\60\0"+
    "\1\52\55\0\1\53\55\0\1\54\51\0\2\25\4\0"+
    "\2\25\3\0\21\25\22\0\2\25\4\0\2\25\3\0"+
    "\12\25\1\55\1\56\5\25\22\0\2\25\4\0\2\25"+
    "\3\0\1\57\7\25\1\60\1\25\1\61\6\25\22\0"+
    "\2\25\4\0\2\25\3\0\10\25\1\62\10\25\22\0"+
    "\2\25\4\0\2\25\3\0\1\32\11\25\1\63\6\25"+
    "\22\0\2\25\4\0\2\25\3\0\5\25\1\64\3\25"+
    "\1\65\7\25\22\0\2\25\4\0\2\25\3\0\4\25"+
    "\1\66\14\25\22\0\2\25\4\0\2\25\3\0\13\25"+
    "\1\67\5\25\22\0\2\25\4\0\2\25\3\0\12\25"+
    "\1\70\6\25\57\0\1\71\10\0\1\72\46\0\2\47"+
    "\2\0\52\47\17\0\2\73\4\0\1\73\4\0\6\73"+
    "\35\0\2\25\4\0\2\25\3\0\12\25\1\74\6\25"+
    "\22\0\2\25\4\0\2\25\3\0\4\25\1\75\14\25"+
    "\22\0\2\25\4\0\2\25\3\0\10\25\1\76\10\25"+
    "\22\0\2\25\4\0\2\25\3\0\1\77\20\25\22\0"+
    "\2\25\4\0\2\25\3\0\11\25\1\100\7\25\22\0"+
    "\2\25\4\0\2\25\3\0\14\25\1\101\4\25\22\0"+
    "\2\25\4\0\2\25\3\0\13\25\1\64\5\25\22\0"+
    "\2\25\4\0\2\25\3\0\15\25\1\64\3\25\22\0"+
    "\2\25\4\0\2\25\3\0\15\25\1\102\3\25\22\0"+
    "\2\25\4\0\2\25\3\0\16\25\1\101\2\25\22\0"+
    "\2\25\4\0\2\25\3\0\6\25\1\103\12\25\22\0"+
    "\2\25\4\0\2\25\3\0\10\25\1\104\10\25\22\0"+
    "\2\25\4\0\2\25\3\0\1\105\20\25\22\0\2\25"+
    "\4\0\2\25\3\0\10\25\1\106\10\25\22\0\2\25"+
    "\4\0\2\25\3\0\14\25\1\107\4\25\22\0\2\25"+
    "\4\0\2\25\3\0\15\25\1\110\3\25\22\0\2\25"+
    "\4\0\2\25\3\0\4\25\1\64\14\25\22\0\2\25"+
    "\4\0\2\25\3\0\16\25\1\111\2\25\22\0\2\25"+
    "\4\0\2\25\3\0\3\25\1\64\15\25\22\0\2\25"+
    "\4\0\2\25\3\0\4\25\1\112\14\25\22\0\2\25"+
    "\4\0\2\25\3\0\7\25\1\64\11\25\22\0\2\25"+
    "\4\0\2\25\3\0\12\25\1\113\6\25\22\0\2\25"+
    "\4\0\2\25\3\0\14\25\1\64\4\25\22\0\2\25"+
    "\4\0\2\25\3\0\6\25\1\114\12\25\22\0\2\25"+
    "\4\0\2\25\3\0\13\25\1\115\5\25\22\0\2\25"+
    "\4\0\2\25\3\0\1\115\20\25\22\0\2\25\4\0"+
    "\2\25\3\0\16\25\1\65\2\25\22\0\2\25\4\0"+
    "\2\25\3\0\11\25\1\67\7\25\22\0\2\25\4\0"+
    "\2\25\3\0\11\25\1\64\7\25\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2484];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\7\11\2\1\1\11\4\1\2\11"+
    "\10\1\1\11\1\1\2\11\1\0\2\11\3\0\3\11"+
    "\14\1\2\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Row and Column tracking if needed
    int currentRow = 1;
    int currentCol = 1;

    private boolean isKeyword(String text) {
    String[] keywords = {"class", "int", "if", "else", "break", "boolean", "void", "for", "return", "true", "false", "continue","callout"};
    for (String keyword : keywords) {
        if (keyword.equals(text)) {
            return true;
        }
    }
    return false;
    }

    private int getKeywordTokenType(String keyword) {
    switch (keyword) {
        case "if":
            return Sym.If;
        case "int":
            return Sym.Int;
        case "class":
            return Sym.Class;
        case "boolean":
            return Sym.Boolean;
        case "void":
            return Sym.Void;
        case "else":
            return Sym.Else;
        case "for":
            return Sym.For;
        case "return":
            return Sym.Return;
        case "true":
            return Sym.True;
        case "false":
            return Sym.False;
        case "break":
            return Sym.Break;
        case "continue":
            return Sym.Continue;
        case "callout":
            return Sym.Callout;
        default:
            return 0; // Return 0 or an appropriate error code for unrecognized keywords
        }
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  GeneratedLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new java_cup.runtime.Symbol(Sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalArgumentException("Illegal character <" + yytext() + ">");
            }
          // fall through
          case 31: break;
          case 2:
            { /* Ignore white space */
            }
          // fall through
          case 32: break;
          case 3:
            { return new java_cup.runtime.Symbol(Sym.Exclam, yyline, yycolumn, yytext());
            }
          // fall through
          case 33: break;
          case 4:
            { return new java_cup.runtime.Symbol(Sym.LeftParent, yyline, yycolumn, yytext());
            }
          // fall through
          case 34: break;
          case 5:
            { return new java_cup.runtime.Symbol(Sym.RightParent, yyline, yycolumn, yytext());
            }
          // fall through
          case 35: break;
          case 6:
            { return new java_cup.runtime.Symbol(Sym.Multiplication, yyline, yycolumn, yytext());
            }
          // fall through
          case 36: break;
          case 7:
            { return new java_cup.runtime.Symbol(Sym.Add, yyline, yycolumn, yytext());
            }
          // fall through
          case 37: break;
          case 8:
            { return new java_cup.runtime.Symbol(Sym.Comma, yyline, yycolumn, yytext());
            }
          // fall through
          case 38: break;
          case 9:
            { return new java_cup.runtime.Symbol(Sym.Substract, yyline, yycolumn, yytext());
            }
          // fall through
          case 39: break;
          case 10:
            { return new java_cup.runtime.Symbol(Sym.Division, yyline, yycolumn, yytext());
            }
          // fall through
          case 40: break;
          case 11:
            { return new java_cup.runtime.Symbol(Sym.DecimalLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 41: break;
          case 12:
            { return new java_cup.runtime.Symbol(Sym.SemiColom, yyline, yycolumn, yytext());
            }
          // fall through
          case 42: break;
          case 13:
            { return new java_cup.runtime.Symbol(Sym.LessThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 43: break;
          case 14:
            { return new java_cup.runtime.Symbol(Sym.Asign, yyline, yycolumn, yytext());
            }
          // fall through
          case 44: break;
          case 15:
            { return new java_cup.runtime.Symbol(Sym.GreaterThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 45: break;
          case 16:
            { return new java_cup.runtime.Symbol(Sym.Id, yyline, yycolumn, yytext());
            }
          // fall through
          case 46: break;
          case 17:
            { return new java_cup.runtime.Symbol(Sym.LeftBracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 47: break;
          case 18:
            { return new java_cup.runtime.Symbol(Sym.RightBracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 48: break;
          case 19:
            { return new java_cup.runtime.Symbol(Sym.LeftKey, yyline, yycolumn, yytext());
            }
          // fall through
          case 49: break;
          case 20:
            { return new java_cup.runtime.Symbol(Sym.RightKey, yyline, yycolumn, yytext());
            }
          // fall through
          case 50: break;
          case 21:
            { return new java_cup.runtime.Symbol(Sym.NotEqual, yyline, yycolumn, yytext());
            }
          // fall through
          case 51: break;
          case 22:
            { return new java_cup.runtime.Symbol(Sym.StringLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 23:
            { return new java_cup.runtime.Symbol(Sym.And, yyline, yycolumn, yytext());
            }
          // fall through
          case 53: break;
          case 24:
            { return new java_cup.runtime.Symbol(Sym.LessEqualThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 25:
            { return new java_cup.runtime.Symbol(Sym.Equal, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 26:
            { return new java_cup.runtime.Symbol(Sym.GreaterEqualThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 27:
            { switch (yytext()) {
        case "class":
            return new java_cup.runtime.Symbol(Sym.Class, yyline, yycolumn);
        case "int":
            return new java_cup.runtime.Symbol(Sym.Int, yyline, yycolumn);
        case "if":
            return new java_cup.runtime.Symbol(Sym.If, yyline, yycolumn);
        case "else":
            return new java_cup.runtime.Symbol(Sym.Else, yyline, yycolumn);
        case "break":
            return new java_cup.runtime.Symbol(Sym.Break, yyline, yycolumn);
        case "boolean":
            return new java_cup.runtime.Symbol(Sym.Boolean, yyline, yycolumn);
        case "for":
            return new java_cup.runtime.Symbol(Sym.For, yyline, yycolumn);
        case "return":
            return new java_cup.runtime.Symbol(Sym.Return, yyline, yycolumn);
        case "true":
            return new java_cup.runtime.Symbol(Sym.True, yyline, yycolumn);
        case "false":
            return new java_cup.runtime.Symbol(Sym.False, yyline, yycolumn);
        case "continue":
            return new java_cup.runtime.Symbol(Sym.Continue, yyline, yycolumn);
        case "callout":
            return new java_cup.runtime.Symbol(Sym.Callout, yyline, yycolumn);
        default:
            throw new IllegalArgumentException("Unknown keyword: " + yytext());
    }
            }
          // fall through
          case 57: break;
          case 28:
            { return new java_cup.runtime.Symbol(Sym.Or, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 29:
            { return new java_cup.runtime.Symbol(Sym.CharLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 30:
            { return new java_cup.runtime.Symbol(Sym.HexLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
