// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: test.jflex


@SuppressWarnings("fallthrough")
class GeneratedLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\3\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\11\21\1\0\1\22"+
    "\1\23\1\24\1\25\2\0\6\26\6\27\1\30\15\27"+
    "\1\31\1\32\1\33\1\0\1\27\1\0\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\2\27\1\42\1\27\1\43"+
    "\1\44\1\27\1\45\1\46\2\27\1\47\1\50\1\51"+
    "\1\52\1\53\1\27\1\54\2\27\1\55\1\56\1\57"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\2\21\1\22\1\23\10\21\1\24\1\1"+
    "\1\25\1\26\1\0\1\27\1\30\3\0\1\31\1\32"+
    "\1\33\11\21\1\34\4\21\1\35\1\36\1\37\10\21"+
    "\1\40\1\41\3\21\1\42\5\21\1\43\2\21\1\44"+
    "\1\45\1\21\1\46\1\21\1\47\1\21\1\50\4\21"+
    "\1\51\1\52\1\53\1\21\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\60\0\u0150"+
    "\0\u0180\0\60\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\60"+
    "\0\60\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0"+
    "\0\u03f0\0\60\0\u0420\0\60\0\60\0\300\0\60\0\60"+
    "\0\u0450\0\u0480\0\u04b0\0\60\0\60\0\60\0\u04e0\0\u0510"+
    "\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0240"+
    "\0\u0690\0\u06c0\0\u06f0\0\u0720\0\60\0\60\0\u04b0\0\u0750"+
    "\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u0240"+
    "\0\u0240\0\u08d0\0\u0900\0\u0930\0\u0240\0\u0960\0\u0990\0\u09c0"+
    "\0\u09f0\0\u0a20\0\u0240\0\u0a50\0\u0a80\0\u0240\0\u0240\0\u0ab0"+
    "\0\u0240\0\u0ae0\0\u0240\0\u0b10\0\u0240\0\u0b40\0\u0b70\0\u0ba0"+
    "\0\u0bd0\0\u0240\0\u0240\0\u0240\0\u0c00\0\u0240";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\2\26\1\27\1\30"+
    "\1\2\1\31\1\26\1\32\1\33\1\26\1\34\1\35"+
    "\1\36\4\26\1\37\1\26\1\40\1\26\1\41\1\26"+
    "\1\42\1\43\1\44\61\0\2\3\101\0\1\45\33\0"+
    "\5\46\1\47\52\46\6\0\1\50\51\0\7\51\1\0"+
    "\22\51\1\52\25\51\20\0\2\21\32\0\1\53\23\0"+
    "\2\21\62\0\1\54\57\0\1\55\57\0\1\56\53\0"+
    "\2\26\4\0\3\26\3\0\21\26\23\0\2\26\4\0"+
    "\3\26\3\0\1\57\20\26\23\0\2\26\4\0\3\26"+
    "\3\0\12\26\1\60\1\61\5\26\23\0\2\26\4\0"+
    "\3\26\3\0\1\62\7\26\1\63\1\26\1\64\6\26"+
    "\23\0\2\26\4\0\3\26\3\0\10\26\1\65\10\26"+
    "\23\0\2\26\4\0\3\26\3\0\1\66\11\26\1\67"+
    "\6\26\23\0\2\26\4\0\3\26\3\0\5\26\1\70"+
    "\3\26\1\71\7\26\23\0\2\26\4\0\3\26\3\0"+
    "\4\26\1\72\14\26\23\0\2\26\4\0\3\26\3\0"+
    "\13\26\1\73\5\26\23\0\2\26\4\0\3\26\3\0"+
    "\12\26\1\74\6\26\61\0\1\75\10\0\1\76\50\0"+
    "\2\51\2\0\54\51\20\0\2\77\4\0\1\77\5\0"+
    "\6\77\36\0\2\26\4\0\3\26\3\0\6\26\1\100"+
    "\12\26\23\0\2\26\4\0\3\26\3\0\12\26\1\101"+
    "\6\26\23\0\2\26\4\0\3\26\3\0\4\26\1\102"+
    "\14\26\23\0\2\26\4\0\3\26\3\0\10\26\1\103"+
    "\10\26\23\0\2\26\4\0\3\26\3\0\1\104\20\26"+
    "\23\0\2\26\4\0\3\26\3\0\11\26\1\105\7\26"+
    "\23\0\2\26\4\0\3\26\3\0\14\26\1\106\4\26"+
    "\23\0\2\26\4\0\3\26\3\0\10\26\1\107\10\26"+
    "\23\0\2\26\4\0\3\26\3\0\13\26\1\110\5\26"+
    "\23\0\2\26\4\0\3\26\3\0\15\26\1\111\3\26"+
    "\23\0\2\26\4\0\3\26\3\0\15\26\1\112\3\26"+
    "\23\0\2\26\4\0\3\26\3\0\16\26\1\113\2\26"+
    "\23\0\2\26\4\0\3\26\3\0\6\26\1\114\12\26"+
    "\23\0\2\26\4\0\3\26\3\0\11\26\1\115\7\26"+
    "\23\0\2\26\4\0\3\26\3\0\10\26\1\116\10\26"+
    "\23\0\2\26\4\0\3\26\3\0\1\117\20\26\23\0"+
    "\2\26\4\0\3\26\3\0\10\26\1\120\10\26\23\0"+
    "\2\26\4\0\3\26\3\0\14\26\1\121\4\26\23\0"+
    "\2\26\4\0\3\26\3\0\15\26\1\122\3\26\23\0"+
    "\2\26\4\0\3\26\3\0\4\26\1\123\14\26\23\0"+
    "\2\26\4\0\3\26\3\0\14\26\1\124\4\26\23\0"+
    "\2\26\4\0\3\26\3\0\16\26\1\125\2\26\23\0"+
    "\2\26\4\0\3\26\3\0\4\26\1\126\14\26\23\0"+
    "\2\26\4\0\3\26\3\0\3\26\1\127\15\26\23\0"+
    "\2\26\4\0\3\26\3\0\4\26\1\130\14\26\23\0"+
    "\2\26\4\0\3\26\3\0\7\26\1\131\11\26\23\0"+
    "\2\26\4\0\3\26\3\0\12\26\1\132\6\26\23\0"+
    "\2\26\4\0\3\26\3\0\14\26\1\133\4\26\23\0"+
    "\2\26\4\0\3\26\3\0\6\26\1\134\12\26\23\0"+
    "\2\26\4\0\3\26\3\0\4\26\1\135\14\26\23\0"+
    "\2\26\4\0\3\26\3\0\13\26\1\136\5\26\23\0"+
    "\2\26\4\0\3\26\3\0\1\137\20\26\23\0\2\26"+
    "\4\0\3\26\3\0\16\26\1\140\2\26\23\0\2\26"+
    "\4\0\3\26\3\0\11\26\1\141\7\26\23\0\2\26"+
    "\4\0\3\26\3\0\11\26\1\142\7\26\23\0\2\26"+
    "\4\0\3\26\3\0\11\26\1\143\7\26\23\0\2\26"+
    "\4\0\3\26\3\0\15\26\1\144\3\26\23\0\2\26"+
    "\4\0\3\26\3\0\16\26\1\145\2\26\23\0\2\26"+
    "\4\0\3\26\3\0\4\26\1\146\14\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3120];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\10\11\2\1\1\11\5\1\2\11"+
    "\10\1\1\11\1\1\2\11\1\0\2\11\3\0\3\11"+
    "\16\1\2\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Row and Column tracking if needed
    int currentRow = 1;
    int currentCol = 1;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  GeneratedLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new java_cup.runtime.Symbol(Sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalArgumentException("Illegal character <" + yytext() + ">");
            }
          // fall through
          case 45: break;
          case 2:
            { /* Ignore white space */
            }
          // fall through
          case 46: break;
          case 3:
            { return new java_cup.runtime.Symbol(Sym.Exclam, yyline, yycolumn, yytext());
            }
          // fall through
          case 47: break;
          case 4:
            { return new java_cup.runtime.Symbol(Sym.LeftParent, yyline, yycolumn, yytext());
            }
          // fall through
          case 48: break;
          case 5:
            { return new java_cup.runtime.Symbol(Sym.RightParent, yyline, yycolumn, yytext());
            }
          // fall through
          case 49: break;
          case 6:
            { return new java_cup.runtime.Symbol(Sym.Multiplication, yyline, yycolumn, yytext());
            }
          // fall through
          case 50: break;
          case 7:
            { return new java_cup.runtime.Symbol(Sym.Add, yyline, yycolumn, yytext());
            }
          // fall through
          case 51: break;
          case 8:
            { return new java_cup.runtime.Symbol(Sym.Comma, yyline, yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 9:
            { return new java_cup.runtime.Symbol(Sym.Substract, yyline, yycolumn, yytext());
            }
          // fall through
          case 53: break;
          case 10:
            { return new java_cup.runtime.Symbol(Sym.Dot, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 11:
            { return new java_cup.runtime.Symbol(Sym.Division, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 12:
            { return new java_cup.runtime.Symbol(Sym.DecimalLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 13:
            { return new java_cup.runtime.Symbol(Sym.SemiColom, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 14:
            { return new java_cup.runtime.Symbol(Sym.LessThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 15:
            { return new java_cup.runtime.Symbol(Sym.Asign, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 16:
            { return new java_cup.runtime.Symbol(Sym.GreaterThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 17:
            { return new java_cup.runtime.Symbol(Sym.Id, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 18:
            { return new java_cup.runtime.Symbol(Sym.LeftBracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 19:
            { return new java_cup.runtime.Symbol(Sym.RightBracket, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 20:
            { return new java_cup.runtime.Symbol(Sym.LeftKey, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 21:
            { return new java_cup.runtime.Symbol(Sym.RightKey, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 22:
            { return new java_cup.runtime.Symbol(Sym.NotEqual, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 23:
            { return new java_cup.runtime.Symbol(Sym.StringLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 24:
            { return new java_cup.runtime.Symbol(Sym.And, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 25:
            { return new java_cup.runtime.Symbol(Sym.LessEqualThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 26:
            { return new java_cup.runtime.Symbol(Sym.Equal, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 27:
            { return new java_cup.runtime.Symbol(Sym.GreaterEqualThan, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 28:
            { return new java_cup.runtime.Symbol(Sym.If, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 29:
            { return new java_cup.runtime.Symbol(Sym.Or, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 30:
            { return new java_cup.runtime.Symbol(Sym.CharLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 31:
            { return new java_cup.runtime.Symbol(Sym.HexLiteral, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 32:
            { return new java_cup.runtime.Symbol(Sym.For, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 33:
            { return new java_cup.runtime.Symbol(Sym.Int, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 34:
            { return new java_cup.runtime.Symbol(Sym.Program, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 35:
            { return new java_cup.runtime.Symbol(Sym.Else, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 36:
            { return new java_cup.runtime.Symbol(Sym.True, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 37:
            { return new java_cup.runtime.Symbol(Sym.Void, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 38:
            { return new java_cup.runtime.Symbol(Sym.Break, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 39:
            { return new java_cup.runtime.Symbol(Sym.Class, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 40:
            { return new java_cup.runtime.Symbol(Sym.False, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 41:
            { return new java_cup.runtime.Symbol(Sym.Return, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 42:
            { return new java_cup.runtime.Symbol(Sym.Boolean, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 43:
            { return new java_cup.runtime.Symbol(Sym.Callout, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 44:
            { return new java_cup.runtime.Symbol(Sym.Continue, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
