
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int Comma = 41;
  public static final int Or = 29;
  public static final int Class = 2;
  public static final int True = 13;
  public static final int Exclam = 40;
  public static final int RightKey = 36;
  public static final int SemiColom = 30;
  public static final int LeftKey = 35;
  public static final int If = 7;
  public static final int DecimalLiteral = 48;
  public static final int Id = 46;
  public static final int ParentOpenClose = 37;
  public static final int Void = 4;
  public static final int GreaterThan = 23;
  public static final int Equal = 26;
  public static final int CharLiteral = 45;
  public static final int LeftBracket = 33;
  public static final int Else = 8;
  public static final int Break = 11;
  public static final int StringLiteral = 44;
  public static final int AsignAdd = 16;
  public static final int RightBracket = 34;
  public static final int AsignSubs = 17;
  public static final int Return = 10;
  public static final int NotEqual = 27;
  public static final int Substract = 19;
  public static final int Division = 21;
  public static final int Int = 5;
  public static final int LessEqualThan = 24;
  public static final int HexLiteral = 47;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int Asign = 15;
  public static final int And = 28;
  public static final int error = 1;
  public static final int GreaterEqualThan = 25;
  public static final int False = 14;
  public static final int ERROR = 42;
  public static final int KeyOpenClose = 38;
  public static final int RightParent = 32;
  public static final int Continue = 12;
  public static final int Dot = 43;
  public static final int LessThan = 22;
  public static final int Callout = 39;
  public static final int Add = 18;
  public static final int LeftParent = 31;
  public static final int Multiplication = 20;
  public static final int Boolean = 6;
  public static final int Program = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Class",
  "Program",
  "Void",
  "Int",
  "Boolean",
  "If",
  "Else",
  "For",
  "Return",
  "Break",
  "Continue",
  "True",
  "False",
  "Asign",
  "AsignAdd",
  "AsignSubs",
  "Add",
  "Substract",
  "Multiplication",
  "Division",
  "LessThan",
  "GreaterThan",
  "LessEqualThan",
  "GreaterEqualThan",
  "Equal",
  "NotEqual",
  "And",
  "Or",
  "SemiColom",
  "LeftParent",
  "RightParent",
  "LeftBracket",
  "RightBracket",
  "LeftKey",
  "RightKey",
  "ParentOpenClose",
  "KeyOpenClose",
  "Callout",
  "Exclam",
  "Comma",
  "ERROR",
  "Dot",
  "StringLiteral",
  "CharLiteral",
  "Id",
  "HexLiteral",
  "DecimalLiteral"
  };
}

